const STATES= {
    "Andaman & Nicobar Islands": [
        "Andaman & Nicobar Islands"
    ],
    "Andhra Pradesh": [
        "Amalapuram",
        "Anakapalli",
        "Anantapur",
        "Aruku",
        "Bapatla",
        "Chittoor",
        "Eluru",
        "Guntur",
        "Hindupur",
        "Kadapa",
        "Kakinada",
        "Kurnool",
        "Machilipatnam",
        "Nandyal",
        "Narasaraopet",
        "Narsapuram",
        "Nellore",
        "Ongole",
        "Rajahmundry",
        "Rajampet",
        "Srikakulam",
        "Tirupati",
        "Vijayawada",
        "Visakhapatnam",
        "Vizianagaram"
    ],
    "Arunachal Pradesh": [
        "Arunachal East",
        "Arunachal West"
    ],
    "Assam": [
        "Barpeta",
        "Darrang-Udalguri",
        "Dhubri",
        "Dibrugarh",
        "Diphu (ST)",
        "Guwahati",
        "Jorhat",
        "Karimganj",
        "Kaziranga",
        "Kokrajhar (ST)",
        "Lakhimpur",
        "Nagaon",
        "Silchar (SC)",
        "Sonitpur"
    ],
    "Bihar": [
        "Araria",
        "Arrah",
        "Aurangabad",
        "Banka",
        "Begusarai",
        "Bhagalpur",
        "Buxar",
        "Darbhanga",
        "Gaya",
        "Gopalganj",
        "Hajipur",
        "Jahanabad",
        "Jamui",
        "Jhanjharpur",
        "Karakat",
        "Katihar",
        "Khagaria",
        "Kishanganj",
        "Madhepura",
        "Madhubani",
        "Maharajganj",
        "Munger",
        "Muzaffarpur",
        "Nalanda",
        "Nawada",
        "Paschim Champaran",
        "Pataliputra",
        "Patna Sahib",
        "Purnia",
        "Purvi Champaran",
        "Samastipur",
        "Saran",
        "Sasaram",
        "Sheohar",
        "Sitamarhi",
        "Siwan",
        "Supaul",
        "Ujiarpur",
        "Vaishali",
        "Valmiki Nagar"
    ],
    "Chandigarh": [
        "Chandigarh"
    ],
    "Chhattisgarh": [
        "Bastar",
        "Bilaspur",
        "Durg",
        "Janjgir-Champa",
        "Kanker",
        "Korba",
        "Mahasamund",
        "Raigarh",
        "Raipur",
        "Rajnandgaon",
        "Sarguja"
    ],
    "Dadra and Nagar Haveli and Daman and Diu": [
        "Dadra and Nagar Haveli",
        "Daman and Diu"
    ],
    "Delhi": [
        "Chandni Chowk",
        "East Delhi",
        "New Delhi",
        "North East Delhi",
        "North West Delhi",
        "South Delhi",
        "West Delhi"
    ],
    "Goa": [
        "North Goa",
        "South Goa"
    ],
    "Gujarat": [
        "Ahmedabad East",
        "Ahmedabad West",
        "Amreli",
        "Anand",
        "Banaskantha",
        "Bardoli",
        "Bharuch",
        "Bhavnagar",
        "Chhota Udaipur",
        "Dahod",
        "Gandhinagar",
        "Jamnagar",
        "Junagadh",
        "Kachchh",
        "Kheda",
        "Mahesana",
        "Navsari",
        "Panchmahal",
        "Patan",
        "Porbandar",
        "Rajkot",
        "Sabarkantha",
        "Surat",
        "Surendranagar",
        "Vadodara",
        "Valsad"
    ],
    "Haryana": [
        "Ambala",
        "Bhiwani-Mahendragarh",
        "Faridabad",
        "Gurgaon",
        "Hisar",
        "Karnal",
        "Kurukshetra",
        "Rohtak",
        "Sirsa",
        "Sonipat"
    ],
    "Himachal Pradesh": [
        "Hamirpur",
        "Kangra",
        "Mandi",
        "Shimla"
    ],
    "Jammu and Kashmir": [
        "Anantnag - Rajouri",
        "Baramulla",
        "Jammu",
        "Srinagar",
        "Udhampur"
    ],
    "Jharkhand": [
        "Chatra",
        "Dhanbad",
        "Dumka",
        "Giridih",
        "Godda",
        "Hazaribagh",
        "Jamshedpur",
        "Khunti",
        "Kodarma",
        "Lohardaga",
        "Palamau",
        "Rajmahal",
        "Ranchi",
        "Singhbhum"
    ],
    "Karnataka": [
        "Bagalkot",
        "Bangalore Central",
        "Bangalore North",
        "Bangalore Rural",
        "Bangalore South",
        "Belgaum",
        "Bellary",
        "Bidar",
        "Bijapur",
        "Chamarajanagar",
        "Chikkballapur",
        "Chikkodi",
        "Chitradurga",
        "Dakshina Kannada",
        "Davanagere",
        "Dharwad",
        "Gulbarga",
        "Hassan",
        "Haveri",
        "Kolar",
        "Koppal",
        "Mandya",
        "Mysore",
        "Raichur",
        "Shimoga",
        "Tumkur",
        "Udupi Chikmagalur",
        "Uttara Kannada"
    ],
    "Kerala": [
        "Alappuzha",
        "Alathur",
        "Attingal",
        "Chalakudy",
        "Ernakulam",
        "Idukki",
        "Kannur",
        "Kasaragod",
        "Kollam",
        "Kottayam",
        "Kozhikode",
        "Malappuram",
        "Mavelikkara",
        "Palakkad",
        "Pathanamthitta",
        "Ponnani",
        "Thiruvananthapuram",
        "Thrissur",
        "Vadakara",
        "Wayanad"
    ],
    "Ladakh": [
        "Ladakh"
    ],
    "Lakshadweep": [
        "Lakshadweep"
    ],
    "Madhya Pradesh": [
        "Balaghat",
        "Betul",
        "Bhind",
        "Bhopal",
        "Chhindwara",
        "Damoh",
        "Dewas",
        "Dhar",
        "Guna",
        "Gwalior",
        "Hoshangabad",
        "Indore",
        "Jabalpur",
        "Khajuraho",
        "Khandwa",
        "Khargone",
        "Mandla",
        "Mandsour",
        "Morena",
        "Rajgarh",
        "Ratlam",
        "Rewa",
        "Sagar",
        "Satna",
        "Shahdol",
        "Sidhi",
        "Tikamgarh",
        "Ujjain",
        "Vidisha"
    ],
    "Maharashtra": [
        "Ahmadnagar",
        "Akola",
        "Amravati",
        "Aurangabad",
        "Baramati",
        "Beed",
        "Bhandara - Gondiya",
        "Bhiwandi",
        "Buldhana",
        "Chandrapur",
        "Dhule",
        "Dindori",
        "Gadchiroli-Chimur",
        "Hatkanangle",
        "Hingoli",
        "Jalgaon",
        "Jalna",
        "Kalyan",
        "Kolhapur",
        "Latur",
        "Madha",
        "Maval",
        "Mumbai North",
        "Mumbai North Central",
        "Mumbai North East",
        "Mumbai North West",
        "Mumbai South",
        "Mumbai South Central",
        "Nagpur",
        "Nanded",
        "Nandurbar",
        "Nashik",
        "Osmanabad",
        "Palghar",
        "Parbhani",
        "Pune",
        "Raigad",
        "Ramtek",
        "Ratnagiri - Sindhudurg",
        "Raver",
        "Sangli",
        "Satara",
        "Shirdi",
        "Shirur",
        "Solapur",
        "Thane",
        "Wardha",
        "Yavatmal-Washim"
    ],
    "Manipur": [
        "Inner Manipur",
        "Outer Manipur"
    ],
    "Meghalaya": [
        "Shillong",
        "Tura"
    ],
    "Mizoram": [
        "Mizoram"
    ],
    "Nagaland": [
        "Nagaland"
    ],
    "Odisha": [
        "Aska",
        "Balasore",
        "Bargarh",
        "Berhampur",
        "Bhadrak",
        "Bhubaneswar",
        "Bolangir",
        "Cuttack",
        "Dhenkanal",
        "Jagatsinghpur",
        "Jajpur",
        "Kalahandi",
        "Kandhamal",
        "Kendrapara",
        "Keonjhar",
        "Koraput",
        "Mayurbhanj",
        "Nabarangpur",
        "Puri",
        "Sambalpur",
        "Sundargarh"
    ],
    "Puducherry": [
        "Puducherry"
    ],
    "Punjab": [
        "Amritsar",
        "Anandpur Sahib",
        "Bathinda",
        "Faridkot",
        "Fatehgarh Sahib",
        "Firozpur",
        "Gurdaspur",
        "Hoshiarpur",
        "Jalandhar",
        "Khadoor Sahib",
        "Ludhiana",
        "Patiala",
        "Sangrur"
    ],
    "Rajasthan": [
        "Ajmer",
        "Alwar",
        "Banswara",
        "Barmer",
        "Bharatpur",
        "Bhilwara",
        "Bikaner",
        "Chittorgarh",
        "Churu",
        "Dausa",
        "Ganganagar",
        "Jaipur",
        "Jaipur Rural",
        "Jalore",
        "Jhalawar-Baran",
        "Jhunjhunu",
        "Jodhpur",
        "Karauli-Dholpur",
        "Kota",
        "Nagaur",
        "Pali",
        "Rajsamand",
        "Sikar",
        "Tonk-Sawai Madhopur",
        "Udaipur"
    ],
    "Sikkim": [
        "Sikkim"
    ],
    "Tamil Nadu": [
        "Arakkonam",
        "Arani",
        "Chennai Central",
        "Chennai North",
        "Chennai South",
        "Chidambaram",
        "Coimbatore",
        "Cuddalore",
        "Dharmapuri",
        "Dindigul",
        "Erode",
        "Kallakurichi",
        "Kancheepuram",
        "Kanniyakumari",
        "Karur",
        "Krishnagiri",
        "Madurai",
        "Mayiladuthurai",
        "Nagapattinam",
        "Namakkal",
        "Nilgiris",
        "Perambalur",
        "Pollachi",
        "Ramanathapuram",
        "Salem",
        "Sivaganga",
        "Sriperumbudur",
        "Tenkasi",
        "Thanjavur",
        "Theni",
        "Thiruvallur",
        "Thoothukkudi",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruppur",
        "Tiruvannamalai",
        "Vellore",
        "Viluppuram",
        "Virudhunagar"
    ],
    "Telangana": [
        "Adilabad",
        "Bhongir",
        "Chevella",
        "Hyderabad",
        "Karimnagar",
        "Khammam",
        "Mahabubabad",
        "Mahbubnagar",
        "Malkajgiri",
        "Medak",
        "Nagarkurnool",
        "Nalgonda",
        "Nizamabad",
        "Peddapalle",
        "Secundrabad",
        "Warangal",
        "Zahirabad"
    ],
    "Tripura": [
        "Tripura East",
        "Tripura West"
    ],
    "Uttar Pradesh": [
        "Agra",
        "Akbarpur",
        "Aligarh",
        "Allahabad",
        "Ambedkar Nagar",
        "Amethi",
        "Amroha",
        "Aonla",
        "Azamgarh",
        "Badaun",
        "Baghpat",
        "Bahraich",
        "Ballia",
        "Banda",
        "Bansgaon",
        "Barabanki",
        "Bareilly",
        "Basti",
        "Bhadohi",
        "Bijnor",
        "Bulandshahr",
        "Chandauli",
        "Deoria",
        "Dhaurahra",
        "Domariyaganj",
        "Etah",
        "Etawah",
        "Faizabad",
        "Farrukhabad",
        "Fatehpur",
        "Fatehpur Sikri",
        "Firozabad",
        "Gautam Buddha Nagar",
        "Ghaziabad",
        "Ghazipur",
        "Ghosi",
        "Gonda",
        "Gorakhpur",
        "Hamirpur",
        "Hardoi",
        "Hathras",
        "Jalaun",
        "Jaunpur",
        "Jhansi",
        "Kairana",
        "Kaiserganj",
        "Kannauj",
        "Kanpur",
        "Kaushambi",
        "Kheri",
        "Kushi Nagar",
        "Lalganj",
        "Lucknow",
        "Machhlishahr",
        "Maharajganj",
        "Mainpuri",
        "Mathura",
        "Meerut",
        "Mirzapur",
        "Misrikh",
        "Mohanlalganj",
        "Moradabad",
        "Muzaffarnagar",
        "Nagina",
        "Phulpur",
        "Pilibhit",
        "Pratapgarh",
        "Rae Bareli",
        "Rampur",
        "Robertsganj",
        "Saharanpur",
        "Salempur",
        "Sambhal",
        "Sant Kabir Nagar",
        "Shahjahanpur",
        "Shrawasti",
        "Sitapur",
        "Sultanpur",
        "Unnao",
        "Varanasi"
    ],
    "Uttarakhand": [
        "Almora",
        "Garhwal",
        "Hardwar",
        "Nainital-Udhamsingh Nagar",
        "Tehri Garhwal"
    ],
    "West Bengal": [
        "Alipurduars",
        "Arambagh",
        "Asansol",
        "Baharampur",
        "Balurghat",
        "Bangaon",
        "Bankura",
        "Barasat",
        "Bardhaman Durgapur",
        "Bardhaman Purba",
        "Barrackpore",
        "Basirhat",
        "Birbhum",
        "Bishnupur",
        "Bolpur",
        "Cooch Behar",
        "Darjeeling",
        "Diamond Harbour",
        "Dum Dum",
        "Ghatal",
        "Hooghly",
        "Howrah",
        "Jadavpur",
        "Jalpaiguri",
        "Jangipur",
        "Jaynagar",
        "Jhargram",
        "Kanthi",
        "Kolkata Dakshin",
        "Kolkata Uttar",
        "Krishnanagar",
        "Maldaha Dakshin",
        "Maldaha Uttar",
        "Mathurapur",
        "Medinipur",
        "Murshidabad",
        "Purulia",
        "Raiganj",
        "Ranaghat",
        "Srerampur",
        "Tamluk",
        "Uluberia"
    ],
}

module.exports = STATES;